development:
  adapter:  postgis
  pool: 10
  database: tracking_development

test:
  adapter:  postgis
  database: tracking_test

production:
  adapter:  postgis
  pool: 10
  database: tracking_development
